PetWeb/Models/ErrorViewModel.cs
using System;

namespace PetWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PetWeb/Models/PetsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PetWeb.Models
{
    public class PetsViewModel
    {
        public string OwnerName { get; set; }
        public string OwnerGender { get; set; }
        public int OwnerAge { get; set; }
        public string PetName { get; set; }
        public string PetType { get; set; }
        public string City { get; set; }
    }
}

PetWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PetWeb.Models;

namespace PetWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PetWeb/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PetData;
using PetWeb.Services;

namespace PetWeb.Controllers
{
    public class PetsController : Controller
    {
        private readonly IPetViewService _petViewService;
        public PetsController(IPetViewService petViewService)
        {
            _petViewService = petViewService;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["PetTypes"] = _petViewService.GetPetTypes().Select(p => new SelectListItem()
            {
                Value = p,
                Text = p
            })
            .ToList();
            ViewData["Cities"] = _petViewService.GetCities().Select(p => new SelectListItem()
            {
                Value = p,
                Text = p
            })
            .ToList();
            return View(await _petViewService.GetPetsAsync(new SearchCriteria() { }));
        }
        public async Task<IActionResult> PetGrid(string city, string petName, string petType)
        {
            var searchParams = new SearchCriteria()
            {
                City = city,
                PetName = petName,
                PetType = petType
            };
            return PartialView(await _petViewService.GetPetsAsync(searchParams));
        }
    }
}

PetWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PetWeb/Views/Pets/Index.cshtml
@model IEnumerable<PetWeb.Models.PetsViewModel>

@{
    ViewData["Title"] = "View";
}
@section Scripts
{
    <script>
        $(function () {
            var p = document.getElementById("PetTypes_List");
            var c = document.getElementById("City_List");
            $("#subButton").click(function () {
                var name = document.getElementsByName("PetName_Text")[0].value;
                var city = c.options[c.selectedIndex].value;
                var petType = p.options[p.selectedIndex].value;
                $("#petPartial").load("/Pets/PetGrid?city=" + city + "&petName=" + name + "&petType=" + petType);
            });
        });
    </script>
}
<h1>PetView</h1>

<div class="col-md-3"></div>

<div class="col-md-3"></div>
<br />
<br />

   
        <table cellpadding="0" cellspacing="0">
            <tr>
                @{ List<SelectListItem> petTypes = ViewData["PetTypes"] as List<SelectListItem>; }
                @Html.DropDownList("PetTypes_List", petTypes)
            </tr>
            <tr>
                @{ List<SelectListItem> cities = ViewData["Cities"] as List<SelectListItem>; }
                @Html.DropDownList("City_List", cities )
            </tr>
            <tr>
                <td>Search: </td>
                <td>
                    @Html.TextBox("PetName_Text")
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" id="subButton" value="Submit" /></td>
            </tr>
        </table>
    

<div id="petPartial">
    <partial name="PetGrid" for="@Model" />
</div>

PetWeb/Views/Pets/PetGrid.cshtml
@model IEnumerable<PetWeb.Models.PetsViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OwnerGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
        </tr>
}
    </tbody>
</table>

PetWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Pets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PetWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>